name: Generate EPG

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Notify START
        run: |
          curl -s -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_BTO_TOKEN }}/sendMessage \
          -d chat_id=${{ secrets.TELEGRAM_CHAT_ID }} \
          -d text="üöÄ Pornit workflow *Generate EPG* pe GitHub Actions."

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run EPG script
        run: pwsh ./scripts/epg.ps1

      - name: Configure Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"

      - name: Commit changes
        run: |
          git add epg/epg_all.xml epg/epg_all.xml.gz
          git commit -m "Auto-update EPG $(date)" || echo "No changes to commit"

      - name: Push changes
        run: git push
        
      - name: Read channel count
        id: channels
        run: echo "count=$(cat scripts/channel_count.txt)" >> $GITHUB_OUTPUT

        - name: Read no-epg count
  id: noepg
  run: echo "count=$(cat scripts/no_epg_count.txt)" >> $GITHUB_OUTPUT
        
- name: Notify SUCCESS
  if: success()
  run: |
    curl -s -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage \
    -d chat_id=${{ secrets.TELEGRAM_CHAT_ID }} \
    -d text="‚úÖ Workflow *Generate EPG* a rulat cu succes.%0Aüì∫ Canale procesate: ${{ steps.channels.outputs.count }}%0A‚ö†Ô∏è Canale fƒÉrƒÉ EPG: ${{ steps.noepg.outputs.count }}"
    
      - name: Notify FAILURE
        if: failure()
        run: |
          curl -s -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_BTO_TOKEN }}/sendMessage \
          -d chat_id=${{ secrets.TELEGRAM_CHAT_ID }} \
          -d text="‚ùå Workflow *Generate EPG* a e»ôuat. VerificƒÉ logurile √Æn GitHub Actions."
